import Head from "next/head";
import Link from "next/link";

import styles from "../styles/globals.css";

import { fetchWeatherApi } from 'openmeteo';

const params = {
    "latitude": 37.7749,
    "longitude": -122.4194,
    "start_date": "1950-01-01",
    "end_date": "2050-12-31",
    "models": ["CMCC_CM2_VHR4", "FGOALS_f3_H", "HiRAM_SIT_HR", "MRI_AGCM3_2_S", "EC_Earth3P_HR", "MPI_ESM1_2_XR", "NICAM16_8S"],
    "timezone": "America/Los_Angeles",
    "daily": "temperature_2m_max"
};
const url = "https://climate-api.open-meteo.com/v1/climate";
const responses = await fetchWeatherApi(url, params);

// Helper function to form time ranges
const range = (start: number, stop: number, step: number) =>
    Array.from({ length: (stop - start) / step }, (_, i) => start + i * step);

// Process first location. Add a for-loop for multiple locations or weather models
const response = responses[0];

// Attributes for timezone and location
const utcOffsetSeconds = response.utcOffsetSeconds();
const timezone = response.timezone();
const timezoneAbbreviation = response.timezoneAbbreviation();
const latitude = response.latitude();
const longitude = response.longitude();

const daily = response.daily()!;

// Note: The order of weather variables in the URL query and the indices below need to match!
const weatherData = {

    daily: {
        time: range(Number(daily.time()), Number(daily.timeEnd()), daily.interval()).map(
            (t) => new Date((t + utcOffsetSeconds) * 1000)
        ),
        temperature2mMax: daily.variables(0)!.valuesArray()!,
    },

};

// `weatherData` now contains a simple structure with arrays for datetime and weather data
for (let i = 0; i < weatherData.daily.time.length; i++) {
    console.log(
        weatherData.daily.time[i].toISOString(),
        weatherData.daily.temperature2mMax[i]
    );
}

export default function SanFrancisco() {
    return (
        <>
            <Head>
                <title>San Francisco</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
            </main>
        </>
    );
}